### ISSUE TITLE
Base Requirements

### ISSUE THREAD

**Issue by TracySpitler** [TracySpitler/Shopalot#8]
As a [**developer**]
I want to [**setup the base project (MERN)**]
So that [**users will be able to access the home screen using their browser**]

__Functional Requirements:__ 
* [x] Server & Env Vars #10 
* [x] Routing #11 
* [x] Visual Framework #12  
* [x] Render Content #13 
* [x] Callbacks & Request Errors #14 
* [x] Installation Documentation #15  
* [x] CRUD #16 
* [x] Sensitive Information #17 
* [x] Deploy to Heroku #24 
* [x] Models #26

**Comment by TracySpitler** [comment]
__Start App:__
_after clone and npm dependency install, run:_
```npm bin/www```
_or_
```nodemon bin/www```

__Terminal Outut:__
<img width="571" alt="screen shot 2019-01-21 at 12 20 58 pm" src="https://user-images.githubusercontent.com/16790853/51492052-70f99380-1d7e-11e9-9195-f936d6e1d1a6.png">

__Browser Window:__
_@ localhost:3000_
<img width="471" alt="screen shot 2019-01-21 at 1 13 42 pm" src="https://user-images.githubusercontent.com/16790853/51492213-0bf26d80-1d7f-11e9-8b80-44a77d332368.png">
